# Generated by Django 3.2.7 on 2021-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20210904_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='numberRating',
            field=models.IntegerField(default=0),
        ),
    ]
