# Generated by Django 3.2.7 on 2021-09-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_meal_numberrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='numberRating',
        ),
    ]
