# Generated by Django 3.2.6 on 2021-09-02 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('job_type', models.CharField(choices=[('FT', 'FULL TIME'), ('PT', 'PART TIME')], default='FT', max_length=2)),
                ('description', models.TextField(max_length=1000)),
                ('publish_at', models.DateTimeField(auto_now=True)),
                ('vacency', models.IntegerField(default=1)),
                ('salery', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
            ],
        ),
    ]
